name: Terraform Dev Provision

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: class
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Terraform Init
      run: terraform init -backend-config=env/dev/backend.tfvars

    - name: Terraform Plan
      run: terraform plan -var-file=env/dev/main.tfvars

  apply:
    name: Terraform Apply (Manual Approval)
    runs-on: class
    needs: plan
    environment:
      name: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init -backend-config=env/dev/backend.tfvars

    - name: Terraform Apply
      run: terraform apply -var-file=env/dev/main.tfvars -auto-approve

