name: Check Terraform Version

on:
  push:
    branches: [main]

jobs:
  check-terraform-version:
    runs-on: class

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Terraform Version
        run: terraform version
